//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexaEnqueuer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AlexaResponse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlexaResponse() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlexaEnqueuer.Resources.AlexaResponse", typeof(AlexaResponse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string askAfterAction {
            get {
                return ResourceManager.GetString("askAfterAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yor wish is my comand!.
        /// </summary>
        internal static string askAtFirst {
            get {
                return ResourceManager.GetString("askAtFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you need?.
        /// </summary>
        internal static string askForActions {
            get {
                return ResourceManager.GetString("askForActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See you!.
        /// </summary>
        internal static string bye {
            get {
                return ResourceManager.GetString("bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right now you can turn on and off your computer.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented yet. Come back soon.
        /// </summary>
        internal static string notImplemented {
            get {
                return ResourceManager.GetString("notImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t do what you ask.
        /// </summary>
        internal static string orderNotRecognized {
            get {
                return ResourceManager.GetString("orderNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order submitted.
        /// </summary>
        internal static string orderSubmitted {
            get {
                return ResourceManager.GetString("orderSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I can&apos;t understand the request type.
        /// </summary>
        internal static string typeError {
            get {
                return ResourceManager.GetString("typeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who are you? You shouldn&apos;t be here!.
        /// </summary>
        internal static string userNotAllowed {
            get {
                return ResourceManager.GetString("userNotAllowed", resourceCulture);
            }
        }
    }
}
